# Generated by Django 4.2.25 on 2025-10-13 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubricas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluado', models.CharField(help_text='Persona/curso/contexto evaluado', max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contexto', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Cerrada', 'Cerrada')], default='Borrador', max_length=20)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='rubricas.checklist')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(blank=True, choices=[('L', 'Logrado'), ('M', 'Medianamente Logrado'), ('P', 'Por Lograr')], max_length=1)),
                ('marcado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubricas.descriptor')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.evaluacion')),
            ],
            options={
                'unique_together': {('evaluacion', 'descriptor')},
            },
        ),
    ]
