# Generated by Django 4.2.25 on 2025-10-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(default='Plantilla MBE', max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-activo', '-version', 'id'],
                'unique_together': {('nombre', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Estandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estandares', to='rubricas.dominio')),
            ],
            options={
                'ordering': ['dominio__orden', 'orden', 'id'],
                'unique_together': {('dominio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Foco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('estandar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focos', to='rubricas.estandar')),
            ],
            options={
                'ordering': ['estandar__dominio__orden', 'estandar__orden', 'orden', 'id'],
                'unique_together': {('estandar', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('logrado', models.TextField(blank=True, null=True)),
                ('medianamente_logrado', models.TextField(blank=True, null=True)),
                ('por_lograr', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('foco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptores', to='rubricas.foco')),
            ],
            options={
                'ordering': ['foco__estandar__dominio__orden', 'foco__estandar__orden', 'foco__orden', 'orden', 'id'],
                'unique_together': {('foco', 'texto')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rubricas.checklist')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='rubricas.descriptor')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'unique_together': {('checklist', 'descriptor')},
            },
        ),
    ]
