# Generated by Django 4.2.25 on 2025-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
