"""
Django settings for mbe_project project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qd7l9jkw1^16j20lnr59)#9ze*0vl&h)us1*zezoo)7s5u!94='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rubricas',
    'evaluaciones',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mbe_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mbe_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# === Lista de docentes predefinidos (para autocompletar en evaluaciones) ===
DOCENTES_PREDEFINIDOS = [
    "ARAYA ARANCIBIA VALENTINA",
    "ARRIAZA PONCE MARÍA CECILIA",
    "AUGER PONCE MARTINA",
    "BRITO VASQUEZ JOHANNA",
    "CARRASCO BUSTAMANTE JORGE",
    "CARRASCO TAPIA ANAHI",
    "CARRASCO MONTERO SERGIO",
    "CARVAJAL SALINAS ALEJANDRA",
    "CEDEÑO JARA ELIA ROSA",
    "CONTRERAS GODOY MARIBEL",
    "DEL CANTO TOBAR PAULA",
    "DÍAZ ROA NELSON",
    "DONOSO ARQUERO VANESSA",
    "DONOSO OLAVARRIA CHRISTIAN",
    "ESCOBAR RAVEST KARLA",
    "ESCOBAR OLIVARES KATHERINE",
    "FERNÁNDEZ OPAZO CINTIA",
    "FERNÁNDEZ ROSALES JUAN",
    "GÁLVEZ HERNÁNDEZ ALEJANDRA",
    "GONZALEZ BARAHONA MARCELA",
    "GONZÁLEZ ROZAS JONATHAN",
    "GUERRA SALAZAR DAVID",
    "GUERRERO MARHOLZ CLAUDIA",
    "MARHOLZ MEZA HELGA",
    "MARTINEZ MUÑOZ ALICE",
    "MIRANDA DELGADO SEBASTIÁN",
    "MONTT COLLAO ALEJANDRO",
    "MUNILLA TAPIA RICARDO",
    "MUÑOZ FUENTES SEBASTIAN",
    "MUÑOZ ZABALA RUTH",
    "NÚÑEZ SOTOMAYOR GLORIA",
    "OLIVARI SOTO MARGARITA",
    "ORELLANA BELTRÁN GABRIELA",
    "ORNAYO ARAVENA GABRIELA",
    "PONCE ZUÑIGA PAULA",
    "RAMÍREZ CISTERNAS JOCELYN",
    "RIVEROS VALDÉS BÁRBARA",
    "ROJAS GUTIERREZ ROMANET",
    "SARIEGO VELÁSQUEZ EVELYN",
    "SAEZ PONCE KATHERINE",
    "SEREÑO ARIAS NICKOLE",
    "SOTO BUSTAMANTE MÓNICA",
    "SOTO REYES CARLOS",
    "TAPIA SOZA MYRIAM",
    "TOBAR SALAS KATHERINE",
    "TOLEDO FUENZALIDA VERÓNICA",
    "TRUJILLO QUEVEDO CAMILA",
    "VERGARA POBLETE FLABIA",
    "VIANO ROJO MARCELA",
    "ZÚÑIGA CASTILLO JAVIERA",
    "BELLO CARREÑO BÁRBARA (REEMPLAZO)",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
